package Model;

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Created by Akwasi on ${9/27/2018}.
 */

public class RestaurantSubMenuItem implements Parcelable {
    private int menuItemId, subMenuItemId;
    private String subMenuItemDesc, subMenuItemPhoto;

    //    Constructor
    public RestaurantSubMenuItem(int menuItemId, int SubMenuItemId, String SubMenuItemDesc) {
        this.menuItemId = menuItemId;
        this.subMenuItemDesc = SubMenuItemDesc;
        this.subMenuItemId = SubMenuItemId;
    }

//    Constructor
    public RestaurantSubMenuItem(int menuItemId, int subMenuItemId, String SubMenuItemDesc, String SubMenuItemPhoto) {
        this.menuItemId = menuItemId;
        this.subMenuItemId = subMenuItemId;
        this.subMenuItemDesc = SubMenuItemDesc;
        this.subMenuItemPhoto = SubMenuItemPhoto;
    }

    //    Constructor
    public RestaurantSubMenuItem(int menuItemId, String SubMenuItemDesc, String SubMenuItemPhoto) {
        this.menuItemId = menuItemId;
        this.subMenuItemDesc = SubMenuItemDesc;
        this.subMenuItemPhoto = SubMenuItemPhoto;
    }

    //    Constructor
    public RestaurantSubMenuItem(int menuItemId, String SubMenuItemDesc) {
        this.menuItemId = menuItemId;
        this.subMenuItemDesc = SubMenuItemDesc;
    }

    //    Constructor generated by Sys
    protected RestaurantSubMenuItem(Parcel in) {
        menuItemId =  Integer.parseInt(in.readString());
        subMenuItemId = Integer.parseInt(in.readString());
        subMenuItemDesc = in.readString();
        subMenuItemPhoto = in.readString();
    }

    public int getMenuItemId() {
        return menuItemId;
    }

    public int getSubMenuItemId() {
        return subMenuItemId;
    }

    public String getSubMenuItemDesc() {
        return subMenuItemDesc;
    }

    public String getSubMenuItemPhoto() {
        return subMenuItemPhoto;
    }

    public static final Creator<RestaurantSubMenuItem> CREATOR = new Creator<RestaurantSubMenuItem>() {
        @Override
        public RestaurantSubMenuItem createFromParcel(Parcel in) {
            return new RestaurantSubMenuItem(in);
        }

        @Override
        public RestaurantSubMenuItem[] newArray(int size) {
            return new RestaurantSubMenuItem[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(String.valueOf(menuItemId));
        dest.writeString(String.valueOf(subMenuItemId));
        dest.writeString(subMenuItemDesc);
        dest.writeString(subMenuItemPhoto);
    }
}
